const topicOneStepIds=['lesson','html-1-2','html-1-3','html-1-4','html-1-5'];
function showScreen(id){document.body.classList.remove('reading-topic');document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function showTopicOne(){const firstStep=document.getElementById('lesson');if(!firstStep){window.location.href=new URL('topics/html-01.html',document.baseURI).href;return}document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));topicOneStepIds.forEach(id=>document.getElementById(id)?.classList.add('active'));document.getElementById('topicResult')?.classList.remove('active');document.body.classList.add('reading-topic');window.scrollTo({top:0,behavior:'smooth'})}
function goToNextStep(stepId,feedbackId){const nextScreen=document.getElementById(stepId);if(nextScreen){showScreen(stepId);return}const feedback=document.getElementById(feedbackId);feedback.className='feedback show info';feedback.innerHTML='<b>Наступний крок ще не додано.</b> Навігаційний маршрут <code>'+stepId+'</code> готовий: щойно екран кроку буде підключено, кнопка відкриє його без додаткових змін.'}
function answerChoice(button,correct){const feedback=document.getElementById('choiceFeedback'),answers=[...document.querySelectorAll('.answer')],right=answers[1];answers.forEach(x=>x.classList.remove('selected','correct','incorrect'));feedback.className='feedback show '+(correct?'success':'error');if(correct){button.classList.add('selected');feedback.innerHTML='<b>✓ Правильно!</b> HTML не визначає дизайн сторінки та не підключає до інтернету. Воно повідомляє браузеру, що є заголовком, абзацом та іншими частинами вмісту.'}else{button.classList.add('incorrect');right.classList.add('correct');feedback.innerHTML='<b>Спробуй ще раз.</b> HTML допомагає браузеру розпізнати структуру й роль вмісту. Правильний варіант позначено після твоєї відповіді.'}}
function checkPractice(){const code=document.getElementById('practiceCode').value.trim(),feedback=document.getElementById('practiceFeedback'),next=document.getElementById('nextStep'),correct=/<h1>[^<]+<\/h1>/i.test(code);feedback.className='feedback show '+(correct?'success':'error');if(correct){feedback.innerHTML='<b>✓ Крок виконано!</b> Ти позначив/-ла текст як головний заголовок. Браузер зможе зрозуміти його роль на вебсторінці.';next.classList.remove('disabled')}else feedback.innerHTML='<b>Спробуй ще раз.</b> Додай один завершений елемент: <code>&lt;h1&gt;твій заголовок&lt;/h1&gt;</code>.'}
function answerChoiceTwo(button,correct){const feedback=document.getElementById('choiceFeedbackTwo'),answers=[...document.querySelectorAll('.answer-two')],right=answers[0];answers.forEach(x=>x.classList.remove('selected','correct','incorrect'));feedback.className='feedback show '+(correct?'success':'error');if(correct){button.classList.add('selected');feedback.innerHTML='<b>✓ Правильно!</b> HTML-теги допомагають браузеру зрозуміти роль частин вмісту: де заголовок, де абзац та інші елементи сторінки.'}else{button.classList.add('incorrect');right.classList.add('correct');feedback.innerHTML='<b>Спробуй ще раз.</b> Правильний варіант показано після відповіді, щоб можна було порівняти його з обраним.<button class="retry" onclick="resetChoiceTwo()">Повторити спробу</button>'}}
function resetChoiceTwo(){document.querySelectorAll('.answer-two').forEach(x=>x.classList.remove('selected','correct','incorrect'));const feedback=document.getElementById('choiceFeedbackTwo');feedback.className='feedback';feedback.innerHTML=''}
function checkMatching(){const h1=document.getElementById('roleH1').value,p=document.getElementById('roleP').value,feedback=document.getElementById('matchingFeedback'),next=document.getElementById('nextStepTwo'),correct=h1==='heading'&&p==='paragraph';feedback.className='feedback show '+(correct?'success':'error');if(correct){feedback.innerHTML='<b>✓ Крок виконано!</b> <code>&lt;h1&gt;</code> позначає головний заголовок, а <code>&lt;p&gt;</code> — абзац. HTML-розмітка робить ролі частин вебсторінки зрозумілими для браузера.';next.classList.remove('disabled')}else feedback.innerHTML='<b>Спробуй ще раз.</b> Згадай: <code>&lt;h1&gt;</code> використовують для головного заголовка, а <code>&lt;p&gt;</code> — для абзацу.'}
function answerChoiceThree(button,correct){const feedback=document.getElementById('choiceFeedbackThree'),answers=[...document.querySelectorAll('.answer-three')],right=answers[0];answers.forEach(x=>x.classList.remove('selected','correct','incorrect'));feedback.className='feedback show '+(correct?'success':'error');if(correct){button.classList.add('selected');feedback.innerHTML='<b>✓ Правильно!</b> Браузер читає HTML-розмітку, визначає структуру вмісту та відображає результат на вебсторінці.'}else{button.classList.add('incorrect');right.classList.add('correct');feedback.innerHTML='<b>Спробуй ще раз.</b> Правильний варіант показано після відповіді, щоб можна було порівняти його з обраним.<button class="retry" onclick="resetChoiceThree()">Повторити спробу</button>'}}
function resetChoiceThree(){document.querySelectorAll('.answer-three').forEach(x=>x.classList.remove('selected','correct','incorrect'));const feedback=document.getElementById('choiceFeedbackThree');feedback.className='feedback';feedback.innerHTML=''}
let sequence=[];
function addSequenceStep(step,button){if(sequence.includes(step))return;sequence.push(step);button.disabled=true;const labels={html:'HTML-код містить структуру сторінки.',read:'Браузер читає HTML-код.',display:'Браузер відображає вебсторінку.'};document.getElementById('sequenceResult').innerHTML=sequence.map((item,index)=>'<span><b>'+(index+1)+'</b>'+labels[item]+'</span>').join('')}
function checkSequence(){const feedback=document.getElementById('sequenceFeedback'),next=document.getElementById('nextStepThree'),correct=sequence.join(',')==='html,read,display';feedback.className='feedback show '+(correct?'success':'error');if(correct){feedback.innerHTML='<b>✓ Крок виконано!</b> Тепер ти розумієш, як HTML-код пов’язаний із вебсторінкою.<br><span>Саме так: HTML описує структуру, браузер читає цю розмітку, а результат ми бачимо як вебсторінку.</span>';next.classList.remove('disabled')}else feedback.innerHTML='<b>Порядок поки неправильний.</b> Подумай, що відбувається спочатку: код уже містить структуру, а браузер може її прочитати лише після цього.<button class="retry" onclick="resetSequence()">Спробувати ще раз</button>'}
function resetSequence(){sequence=[];document.querySelectorAll('.sequence-options button').forEach(x=>x.disabled=false);document.getElementById('sequenceResult').innerHTML='<span>Твоя послідовність з’явиться тут</span>';const feedback=document.getElementById('sequenceFeedback');feedback.className='feedback';feedback.innerHTML=''}
function answerChoiceFour(button,correct){const feedback=document.getElementById('choiceFeedbackFour'),answers=[...document.querySelectorAll('.answer-four')],right=answers[1];answers.forEach(x=>x.classList.remove('selected','correct','incorrect'));feedback.className='feedback show '+(correct?'success':'error');if(correct){button.classList.add('selected');feedback.innerHTML='<b>✓ Правильно!</b> HTML-елемент може складатися з відкривального тега, вмісту та закривального тега. Разом вони повідомляють браузеру, що це за частина сторінки.'}else{button.classList.add('incorrect');right.classList.add('correct');feedback.innerHTML='<b>Спробуй ще раз.</b> Правильний варіант показано після відповіді, щоб можна було порівняти його з обраним.<button class="retry" onclick="resetChoiceFour()">Повторити спробу</button>'}}
function resetChoiceFour(){document.querySelectorAll('.answer-four').forEach(x=>x.classList.remove('selected','correct','incorrect'));const feedback=document.getElementById('choiceFeedbackFour');feedback.className='feedback';feedback.innerHTML=''}
function checkParts(){const open=document.getElementById('partOpen').value,content=document.getElementById('partContent').value,close=document.getElementById('partClose').value,feedback=document.getElementById('partsFeedback'),correct=open==='open'&&content==='content'&&close==='close';feedback.className='feedback show '+(correct?'success':'error');feedback.innerHTML=correct?'<b>✓ Правильно!</b> Відкривальний тег <code>&lt;h1&gt;</code> і закривальний тег <code>&lt;/h1&gt;</code> визначають елемент, а текст між ними є його вмістом.':'<b>Спробуй ще раз.</b> Прочитай елемент зліва направо: спочатку тег відкриває елемент, потім іде текст, а наприкінці тег закриває його.'}
function answerSummary(button,correct){const feedback=document.getElementById('summaryFeedback'),answers=[...document.querySelectorAll('.answer-summary')],right=answers[1],next=document.getElementById('nextStepFour');answers.forEach(x=>x.classList.remove('selected','correct','incorrect'));feedback.className='feedback show '+(correct?'success':'error');if(correct){button.classList.add('selected');feedback.innerHTML='<b>✓ Крок виконано!</b> Тепер ти розумієш, як браузер читає HTML-елементи та з чого вони складаються.';next.classList.remove('disabled')}else{button.classList.add('incorrect');right.classList.add('correct');feedback.innerHTML='<b>Спробуй ще раз.</b> Для головного заголовка потрібен елемент <code>&lt;h1&gt;...&lt;/h1&gt;</code>.<button class="retry" onclick="resetSummary()">Повторити спробу</button>'}}
function resetSummary(){document.querySelectorAll('.answer-summary').forEach(x=>x.classList.remove('selected','correct','incorrect'));const feedback=document.getElementById('summaryFeedback');feedback.className='feedback';feedback.innerHTML=''}
function checkFinalPractice(){const code=document.getElementById('finalPracticeCode').value,feedback=document.getElementById('finalPracticeFeedback'),next=document.getElementById('nextStepFive'),heading=/<h1>\s*[^<\s][^<]*<\/h1>/i.test(code),paragraph=/<p>\s*[^<\s][^<]*<\/p>/i.test(code),correct=heading&&paragraph;feedback.className='feedback show '+(correct?'success':'error');if(correct){feedback.innerHTML='<b>✓ Крок виконано!</b><br>Ти вже вмієш створювати простий HTML-фрагмент і розумієш, як браузер перетворює HTML-код на вебсторінку.';next.classList.remove('disabled');showThemeResult()}else{let missing=[];if(!heading)missing.push('один завершений заголовок <code>&lt;h1&gt;...&lt;/h1&gt;</code> з текстом');if(!paragraph)missing.push('один завершений абзац <code>&lt;p&gt;...&lt;/p&gt;</code> з текстом');feedback.innerHTML='<b>Спробуй ще раз.</b> Додай '+missing.join(' і ')+'.'}}
const topics=[['Знайомство з HTML','Дізнайся, що таке HTML і як він допомагає створювати вебсторінки.'],['Структура HTML-документа','Розберися з основною структурою HTML-файлу.'],['Заголовки та основний текст','Створюй заголовки та абзаци й організовуй текст вебсторінки.'],['Теги форматування тексту','Форматуй і виділяй важливі частини тексту за допомогою HTML.'],['Цитати та назви творів','Додавай цитати та правильно позначай назви творів.'],['Смислова розмітка тексту','Позначай призначення окремих фрагментів тексту за допомогою HTML.'],['Списки','Створюй марковані, нумеровані та вкладені списки.'],['Гіперпосилання','Додавай посилання та організовуй переходи між сторінками.'],['Зображення','Додавай зображення на вебсторінку та правильно описуй їх.'],['Відео','Додавай відео на вебсторінку та працюй з основними параметрами.'],['Таблиці','Створюй і оформлюй таблиці для структурованого подання даних.'],['Форми','Створюй форми та додавай основні елементи введення даних.'],['Семантична структура','Організовуй структуру вебсторінки за допомогою семантичних HTML-тегів.'],['Підсумковий проєкт «Моя вебсторінка»','Застосуй вивчені HTML-теги у власній вебсторінці.']];
function renderTopics(){const grid=document.getElementById('topicsGrid');if(!grid)return;grid.innerHTML=topics.map((topic,index)=>'<article class="topic-card"><span>'+String(index+1).padStart(2,'0')+'</span><h3>'+topic[0]+'</h3><p>'+topic[1]+'</p><button class="button ghost" onclick="openTopic('+(index+1)+')">Відкрити тему <b>→</b></button></article>').join('')}
function openTopic(number){if(number===1){window.location.href=new URL('topics/html-01.html',document.baseURI).href;return}const topic=topics[number-1];document.getElementById('previewNumber').textContent='Тема '+number+' із 14';document.getElementById('previewTitle').textContent=topic[0];document.getElementById('previewDescription').textContent=topic[1];showScreen('topicPreview')}
function showThemeResult(){const result=document.getElementById('topicResult');result.classList.add('active');setTimeout(()=>result.scrollIntoView({behavior:'smooth',block:'start'}),0)}
function repeatTopicOne(){document.getElementById('topicResult')?.classList.remove('active');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.crumb button[onclick="showScreen(\'home\')"],.task-footer .ghost[onclick="showScreen(\'home\')"]').forEach(button=>button.innerHTML='← До всіх тем');
renderTopics();
const practiceEditorIds=['practiceCode','finalPracticeCode'];
function clearPracticeEditorsForNewSession(){practiceEditorIds.forEach(id=>{const editor=document.getElementById(id);if(editor){editor.value='';editor.autocomplete='off'}})}
clearPracticeEditorsForNewSession();
window.addEventListener('pageshow',event=>{const navigation=performance.getEntriesByType('navigation')[0];if(event.persisted||navigation?.type==='reload')clearPracticeEditorsForNewSession()});
