const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)],T=window.HTMLSkills;

function reportSelects(card,selector,attribute){const fields=qa(selector,card),wrong=fields.filter(field=>field.value!==field.dataset[attribute]),empty=fields.filter(field=>!field.value);const out=q('.feedback',card);if(!wrong.length)T.feedback(out,'Усі відповідності правильні.',true);else{const details=empty.length?'Не для всіх фрагментів обрано відповідь.':'Помилкових відповідностей: '+wrong.length+'. Перевір кожен фрагмент і спробуй ще раз.';T.feedback(out,details,false)}}
q('[data-check-exercise="1"]').addEventListener('click',()=>reportSelects(q('#exercise-1'),'select','match'));
q('[data-check-exercise="2"]').addEventListener('click',()=>reportSelects(q('#exercise-2'),'select','place'));

const correctOrder=['<!DOCTYPE html>','<html lang="uk">','<head>','<title>Мій улюблений спорт</title>','</head>','<body>','<h1>Футбол</h1>','</body>','</html>'];
let order=['<body>','<title>Мій улюблений спорт</title>','</html>','<head>','<h1>Футбол</h1>','<!DOCTYPE html>','</head>','<html lang="uk">','</body>'],selected=-1;
function renderOrder(){const box=q('#order-list');box.replaceChildren();order.forEach((line,index)=>{const button=document.createElement('button');button.type='button';button.textContent=line;button.className=index===selected?'selected':'';button.addEventListener('click',()=>{selected=index;renderOrder()});box.append(button)})}
function move(delta){if(selected<0)return;const next=selected+delta;if(next<0||next>=order.length)return;[order[selected],order[next]]=[order[next],order[selected]];selected=next;renderOrder()}
q('#move-up').addEventListener('click',()=>move(-1));q('#move-down').addEventListener('click',()=>move(1));renderOrder();
q('[data-check-exercise="3"]').addEventListener('click',()=>{const wrong=order.reduce((list,line,index)=>{if(line!==correctOrder[index])list.push(index+1);return list},[]);T.feedback(q('#exercise-3 .feedback'),wrong.length?'Порядок ще неправильний. Перевір рядки: '+wrong.join(', ')+'.':'HTML-документ зібрано правильно.',wrong.length===0)});

q('[data-check-exercise="4"]').addEventListener('click',()=>{const card=q('#exercise-4'),source=q('textarea',card).value,doc=T.analyzeDocument(source),titleOk=T.hasElement(doc.head,'title','Мої домашні улюбленці'),headingOk=T.hasElement(doc.body,'h1','Домашні улюбленці'),out=q('.feedback',card);if(titleOk&&headingOk)T.feedback(out,'Обидві помилки виправлено: <title> знаходиться в <head>, а <h1> — у <body>.',true);else if(titleOk||headingOk){const left=titleOk?'Головний заголовок <h1> потрібно розмістити в <body>.':'<title> потрібно розмістити всередині <head>.';T.feedback(out,'Одну помилку виправлено, але перевір структуру ще раз. '+left,false)}else T.feedback(out,'<title> потрібно розмістити всередині <head>. Головний заголовок <h1> належить до видимого вмісту сторінки, тому його потрібно розмістити в <body>.',false)});

q('[data-check-exercise="5"]').addEventListener('click',()=>{const card=q('#exercise-5'),result=T.checkElement(q('textarea',card).value,{tag:'title',text:'Моя бібліотека',attrs:{}});T.feedback(q('.feedback',card),result.ok?'Назву HTML-документа додано правильно.':'Потрібен елемент <title> із текстом «Моя бібліотека».',result.ok)});

q('[data-check-exercise="6"]').addEventListener('click',()=>{const card=q('#exercise-6'),doc=T.analyzeDocument(q('textarea',card).value),checks=[['Є <!DOCTYPE html>',doc.doctype],['Є <html lang="uk">',doc.htmlOpen&&doc.htmlClose&&doc.lang==='uk'],['Є <head> і </head>',doc.head!==null&&doc.headClosed],['У <head> є <meta charset="UTF-8">',doc.hasMetaUtf8],['У <head> є правильний <title>',T.hasElement(doc.head,'title','Планети')],['Є <body> і </body>',doc.body!==null&&doc.bodyClosed],['У <body> є правильний <h1>',T.hasElement(doc.body,'h1','Планети Сонячної системи')],['У <body> є правильний <p>',T.hasElement(doc.body,'p','Земля є третьою планетою від Сонця.')]],list=q('.check-list',card);list.replaceChildren();checks.forEach(([text,ok])=>{const li=document.createElement('li');li.className=ok?'ok':'bad';li.textContent=(ok?'✓ ':'Потрібно виправити: ')+text;list.append(li)});const passed=checks.filter(([,ok])=>ok).length;T.feedback(q('.feedback',card),passed===checks.length?'Повний HTML-документ створено правильно.':'Правильно виконано '+passed+' із '+checks.length+' перевірок. Виправ позначені частини та перевір ще раз.',passed===checks.length)});

const explanations=['Саме в <body> знаходиться основний вміст, який браузер показує на сторінці.','<!DOCTYPE html> повідомляє браузеру тип документа.','Назва HTML-документа: Мандрівка Україною.','<title> задає назву HTML-документа, а <h1> — головний заголовок у вмісті сторінки.','Основна мова документа — українська.'];
qa('.check-question').forEach((button,index)=>button.addEventListener('click',()=>{const fieldset=button.closest('fieldset'),textInput=q('.text-answer',fieldset),out=q('.feedback',fieldset);let answered,ok;if(textInput){answered=!!textInput.value.trim();ok=T.compact(textInput.value)==='Мандрівка Україною'}else{const result=T.checkRadio(fieldset);answered=result.answered;ok=result.ok}if(!answered)T.feedback(out,'Спочатку дай відповідь.',false);else T.feedback(out,ok?'Правильно. '+explanations[index]:'Відповідь неправильна. Переглянь відповідне пояснення та спробуй ще раз.',ok)}));
q('#project-guide').addEventListener('click',()=>T.toggle(q('#project-guide'),q('#project-structure')));
