(function(){
  'use strict';
  const T=window.HTMLSkills,q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],esc=value=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function selectTasks(root,items,options){items.forEach((item,index)=>{const row=document.createElement('div');row.className='task-row';row.dataset.interactive='';row.innerHTML='<p><strong>'+(index+1)+'. '+esc(item.prompt)+'</strong></p><select class="answer-select" data-reset-feedback aria-label="Відповідь '+(index+1)+'"><option value="">Обери тег</option>'+options.map(tag=>'<option value="'+tag+'">&lt;'+tag+'&gt;</option>').join('')+'</select><button type="button">Перевірити</button><p class="feedback" aria-live="polite"></p>';const select=q('select',row),feedback=q('.feedback',row);q('button',row).addEventListener('click',()=>{if(!select.value)return T.feedback(feedback,'Спочатку обери відповідь.',false);T.feedback(feedback,select.value===item.answer?item.ok:item.bad,select.value===item.answer)});root.append(row)})}
  selectTasks(q('#meaning-situations'),[
    {prompt:'«Увага! Двері зачиняються автоматично.» Познач «Увага!» як важливу інформацію.',answer:'strong',ok:'Правильно: <strong> позначає важливість попередження.',bad:'Тут важливе саме значення попередження, тому потрібен <strong>, а не просто візуальне виділення.'},
    {prompt:'«Доступні розміри: малий, середній, великий.» Слова потрібно лише виділити для привернення уваги.',answer:'b',ok:'Правильно: <b> привертає увагу без додаткової важливості.',bad:'Ці слова не є попередженням або особливо важливою інформацією. Потрібен <b>.'},
    {prompt:'«Я просив виконати завдання самостійно.» На слові «самостійно» потрібен смисловий наголос.',answer:'em',ok:'Правильно: <em> створює смисловий наголос.',bad:'Тут змінюється смисловий акцент фрази, тому потрібен <em>.'},
    {prompt:'«Слово header означає заголовок або верхню частину.» header — іншомовний термін.',answer:'i',ok:'Правильно: <i> позначає текст іншого характеру, зокрема іншомовний термін.',bad:'Це іншомовний термін, а не смисловий наголос. Потрібен <i>.'}
  ],['strong','b','em','i']);
  selectTasks(q('#quote-situations'),[
    {prompt:'«У статті автор зазначає: “Читання розвиває уяву”.» Цитата є частиною речення.',answer:'q',ok:'Правильно: <q> використовують для короткої цитати всередині речення.',bad:'Цитата коротка й залишається частиною речення, тому потрібен <q>.'},
    {prompt:'На сторінці потрібно окремо показати великий уривок із кількох речень.',answer:'blockquote',ok:'Правильно: <blockquote> створює окремий блок розгорнутої цитати.',bad:'Розгорнута цитата стоїть окремим блоком, тому потрібен <blockquote>.'},
    {prompt:'Потрібно позначити назву книги «Маленький принц».',answer:'cite',ok:'Правильно: <cite> позначає назву твору або джерела.',bad:'Це назва твору, а не сама цитата. Потрібен <cite>.'}
  ],['q','blockquote','cite']);

  qa('.check-radio').forEach(button=>button.addEventListener('click',()=>{const field=button.closest('fieldset'),result=T.checkRadio(field),feedback=q('.feedback',field);if(!result.answered)return T.feedback(feedback,'Спочатку обери відповідь.',false);const isQuote=field.dataset.answer==='quotes',ok=result.ok;T.feedback(feedback,ok?(isQuote?'Правильно: браузер сам додає лапки до <q>, тому ручні лапки зайві.':'Правильно: <cite> позначає «Маленький принц» — назву твору, а не ім’я автора.'):(isQuote?'Проблема в ручних лапках навколо <q>: браузер зазвичай додає їх сам.':'<cite> позначає назву твору або джерела, а не ім’я автора.'),ok)}));

  function directElements(tree,node){return tree.elements(node)}
  function childTags(tree,node){return directElements(tree,node).map(child=>child.tag)}
  function tagsAre(tree,node,tags){const actual=childTags(tree,node);return actual.length===tags.length&&actual.every((tag,index)=>tag===tags[index])}
  function textIs(tree,node,text){return !!node&&tree.text(node)===T.compact(text)}
  function parseSingle(source,tag){const tree=T.parseMarkup(source),nodes=directElements(tree,tree.root);return tree.ok&&nodes.length===1&&nodes[0].tag===tag?{tree,node:nodes[0]}:null}
  function validateAnnouncement(source){const parsed=parseSingle(source,'p');if(!parsed)return false;const {tree,node}=parsed,kids=directElements(tree,node);return tagsAre(tree,node,['del','ins'])&&textIs(tree,node,'Екскурсія відбудеться у середу четвер о 14:00.')&&textIs(tree,kids[0],'середу')&&textIs(tree,kids[1],'четвер')}
  function validateFix(source,kind){const parsed=parseSingle(source,'p');if(!parsed)return false;const {tree,node}=parsed,kids=directElements(tree,node);if(kind==='warning')return tagsAre(tree,node,['strong'])&&textIs(tree,kids[0],'Увага!')&&textIs(tree,node,'Увага! Початок зустрічі змінено.');if(kind==='time')return tagsAre(tree,node,['del','ins'])&&textIs(tree,kids[0],'18:00')&&textIs(tree,kids[1],'17:00')&&textIs(tree,node,'Зустріч розпочнеться о 18:00 17:00.');return tagsAre(tree,node,['q'])&&textIs(tree,kids[0],'Цей фільм для мене особливий.')&&textIs(tree,node,'Режисер сказав: Цей фільм для мене особливий.')&&!/[«»]/.test(source)}

  const fixes=[
    {kind:'warning',title:'Підзавдання 1. Заміни тег навколо «Увага!», щоб позначити важливе попередження.',value:'<p><b>Увага!</b> Початок зустрічі змінено.</p>',ok:'Правильно: важливе «Увага!» позначено тегом <strong>.',bad:'Для важливого попередження потрібен <strong>, а не <b>.'},
    {kind:'time',title:'Підзавдання 2. Познач старий і новий час правильними тегами та розташуй їх у логічному порядку.',value:'<p>Зустріч розпочнеться о <ins>17:00</ins> <del>18:00</del>.</p>',ok:'Правильно: спочатку показано вилучений старий час, потім доданий новий.',bad:'Спочатку має бути старе значення <del>18:00</del>, а потім нове <ins>17:00</ins>.'},
    {kind:'quote',title:'Підзавдання 3. Прибери зайві ручні лапки, залишивши коротку цитату в правильному тегу.',value:'<p>Режисер сказав: «<q>Цей фільм для мене особливий.</q>»</p>',ok:'Правильно: ручні лапки прибрано, коротка цитата залишається в <q>.',bad:'Залиши текст цитати в <q>, але прибери ручні лапки « » навколо нього.'}
  ];
  fixes.forEach(item=>{const row=document.createElement('div');row.className='task-row';row.dataset.interactive='';row.innerHTML='<label><strong>'+item.title+'</strong><textarea class="code-editor" rows="3" data-reset-feedback>'+esc(item.value)+'</textarea></label><button type="button">Перевірити</button><p class="feedback" aria-live="polite"></p>';q('button',row).addEventListener('click',()=>{const ok=validateFix(q('textarea',row).value,item.kind);T.feedback(q('.feedback',row),ok?item.ok:item.bad,ok)});q('#fix-tasks').append(row)});

  function validateFragment(source){const tree=T.parseMarkup(source),nodes=directElements(tree,tree.root);if(!tree.ok||!tagsAre(tree,tree.root,['h2','p']))return{ok:false,checks:[false,false,false,false]};const h2=nodes[0],p=nodes[1],kids=directElements(tree,p),checks=[textIs(tree,h2,'Важлива інформація'),tagsAre(tree,p,['strong','del','ins']),kids.length===3&&textIs(tree,kids[0],'Увага!')&&textIs(tree,kids[1],'12:00')&&textIs(tree,kids[2],'13:00'),textIs(tree,p,'Увага! Час початку майстер-класу змінено з 12:00 на 13:00.')];return{ok:checks.every(Boolean),checks}}
  function validateBookshelf(source){const tree=T.parseMarkup(source),html=tree.find(tree.root,'html'),head=html&&tree.find(html,'head'),body=html&&tree.find(html,'body'),title=head&&tree.find(head,'title'),bodyNodes=body?directElements(tree,body):[],frame=tree.ok&&tree.doctype&&html&&head&&body&&tagsAre(tree,html,['head','body']),titleOk=title&&tagsAre(tree,head,['title'])&&textIs(tree,title,'Моя книжкова полиця'),order=body&&tagsAre(tree,body,['h1','p','h2','p','h2','p']);let texts=false,nested=false;if(order){const [h1,p1,h21,p2,h22,p3]=bodyNodes,k2=directElements(tree,p2),k3=directElements(tree,p3);texts=textIs(tree,h1,'Моя книжкова полиця')&&textIs(tree,p1,'Тут я збираю книги, які хочу прочитати.')&&textIs(tree,h21,'Зараз читаю')&&textIs(tree,p2,'Зараз я читаю книгу Маленький принц Антуана де Сент-Екзюпері.')&&textIs(tree,h22,'Плани змінилися')&&textIs(tree,p3,'Наступною планував прочитати Пригоди Тома Соєра, але тепер обираю Алісу в Країні Див.');nested=tagsAre(tree,p2,['cite'])&&textIs(tree,k2[0],'Маленький принц')&&tagsAre(tree,p3,['del','ins'])&&textIs(tree,k3[0],'Пригоди Тома Соєра')&&textIs(tree,k3[1],'Алісу в Країні Див')}const checks=[!!frame,!!titleOk,!!order,!!texts,!!nested];return{ok:checks.every(Boolean),checks}}
  function renderChecks(card,items,checks){const list=q('.check-list',card);list.replaceChildren();items.forEach((text,index)=>{const li=document.createElement('li');li.className=checks[index]?'ok':'bad';li.textContent=(checks[index]?'✓ ':'Потрібно виправити: ')+text;list.append(li)})}
  qa('[data-check-code]').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('[data-interactive]'),source=q('textarea',card).value,feedback=q('.feedback',card),type=button.dataset.checkCode;if(type==='announcement'){const ok=validateAnnouncement(source);return T.feedback(feedback,ok?'Зміну оголошення позначено правильно: старий день вилучено, новий додано.':'Потрібен один абзац: «середу» познач як вилучене значення, а «четвер» — як додане. Порядок важливий.',ok)}if(type==='fragment'){const result=validateFragment(source);renderChecks(card,['Заголовок другого рівня має правильний текст','У повідомленні правильні вкладені теги strong, del та ins','У вкладених тегах правильні фрагменти тексту','Повний текст абзацу відповідає завданню'],result.checks);return T.feedback(feedback,result.ok?'HTML-фрагмент створено правильно.':'Перевір позначені частини: важливе повідомлення, старий і новий час повинні мати правильні ролі та порядок.',result.ok)}const result=validateBookshelf(source);renderChecks(card,['Є повний каркас документа','У head є правильний title','У body правильний порядок h1, p, h2, p, h2, p','Усі заголовки й абзаци мають правильний текст','cite, del та ins правильно вкладені у відповідні абзаци'],result.checks);T.feedback(feedback,result.ok?'Повний HTML-документ створено правильно.':'Перевір позначені критерії. Теги мають бути не лише присутні, а правильно вкладені у відповідні абзаци.',result.ok)}));

  const quiz=[
    {prompt:'Чим відрізняються <strong> і <b>?',options:['Обидва лише роблять текст жирним.','<strong> позначає важливість, а <b> привертає увагу без додаткової важливості.'],answer:1,ok:'Правильно: обираємо між ними за значенням, а не за жирним виглядом.',bad:'<strong> передає важливість, а <b> лише привертає увагу.'},
    {prompt:'Чим відрізняються <em> та <i>?',options:['<em> створює смисловий наголос, а <i> позначає текст іншого характеру.','Вони завжди означають те саме.'],answer:0,ok:'Правильно: однаковий курсивний вигляд не означає однакову роль.',bad:'<em> — смисловий наголос, <i> — текст іншого характеру, наприклад термін.'},
    {prompt:'Який тег позначає вилучену інформацію?',options:['<ins>','<del>','<b>'],answer:1,ok:'Правильно: <del> позначає вилучений текст.',bad:'Вилучену інформацію позначає <del>.'},
    {prompt:'Коротка цитата знаходиться всередині речення. Який тег використовуємо?',options:['<q>','<blockquote>','<cite>'],answer:0,ok:'Правильно: <q> призначений для короткої цитати в реченні.',bad:'Для короткої цитати всередині речення використовують <q>.'},
    {prompt:'Що позначає <cite>?',options:['Ім’я автора цитати.','Назву твору або джерела.','Будь-який курсивний текст.'],answer:1,ok:'Правильно: <cite> позначає назву твору або джерела.',bad:'<cite> позначає назву твору або джерела, а не ім’я автора.'}
  ];
  const quizRoot=q('#quiz-questions');quiz.forEach((item,index)=>{const field=document.createElement('fieldset');field.className='question-card';field.dataset.interactive='';field.innerHTML='<legend><strong>'+(index+1)+'. '+esc(item.prompt)+'</strong></legend>'+item.options.map((option,i)=>'<label><input type="radio" name="topic4-q'+index+'" value="'+i+'" data-reset-feedback> <span>'+esc(option)+'</span></label>').join('')+'<button type="button">Перевірити</button><p class="feedback" aria-live="polite"></p>';q('button',field).addEventListener('click',()=>{const chosen=q('input:checked',field),feedback=q('.feedback',field);if(!chosen)return T.feedback(feedback,'Спочатку обери відповідь.',false);const ok=Number(chosen.value)===item.answer;T.feedback(feedback,ok?item.ok:item.bad,ok)});quizRoot.append(field)});
  const projectMeaning=q('.project-meaning-question');if(projectMeaning){q('.check-project-meaning',projectMeaning).addEventListener('click',()=>{const result=T.checkRadio(projectMeaning),feedback=q('.feedback',projectMeaning);if(!result.answered)return T.feedback(feedback,'Спочатку обери відповідь.',false);T.feedback(feedback,result.ok?'Правильно: <i> позначає давнє слово як текст іншого характеру.':'Тут слово не є попередженням або смисловим наголосом. Давнє слово доречно позначити тегом <i>.',result.ok)})}
  T.clearFeedbackOnChange(document);
})();
